services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"

    environment:
      DATABASE_HOSTNAME: postgres
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: password123
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: 028340829urj9283ru29rj92ur992uut8349u0tu49u
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: fastapi
    volumes:
      - postify-db:/var/lib/postgresql

volumes:
  postify-db: